### ISSUE TITLE
Serifs eruit

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#701]
Algemeen: serif fonts eruit halen en typografie van design volgen.

Overal waar we een serif font gebruiken, code genre `<h3 class="vl-title vl-title--h3">`, dit vervangen door de `auk`-equivalent.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#701-remove-serif-font

**Comment by brenner-company** [comment]
Mixed met #705:

Binnen het project zijn er nog redelijk veel titels aanwezig van het type `vl-title vl-title--h[#]`. Deze kunnen eventueel ook vervangen worden, maar de pagina's waar ze binnen staan hebben meestal geen design referentie binnen de Figma mockups of het design is aangepast (om te verbeteren/vernieuwen).

Ofwel laten we deze nog staan tot het correcte design geïmplementeerd kan worden ofwel kunnen ze pagina per pagina aangepast worden (daar is enkel wat visuele controle ivm font-size en margins tegenover elementen nodig).

**Comment by Wolfr** [comment]
Van bijna elk scherm bestaat een design hoor; maar zoals je misschien gezien hebt zitten er meestal nog wel meer verbeteringen in dan enkel de titels veranderen.

Maar wachten op een volledige implementatie is niet de bedoeling. Dan gaat het nooit gebeuren. We moeten stapje voor stapje werken. Dus je laatste suggestie is het beste.

**Comment by Wolfr** [comment]
Zoals aangegeven in #705,  lijken unit testen af te hangen van CSS selectors.

Nochtans was er ooit in het project afgesproken om met data attributes te werken. Hier is precies niet echt aan gehouden.

Ik heb de vraag gesteld (of eerder opmerking gegeven) in het algemene dev kanaal.

Ik denk dat je best eens vraagt hoe je die testen kan runnen lokaal aan iemand van het dev team, ik heb hier zelf geen ervaring mee.

**Comment by Wolfr** [comment]
Lijkt me goed, ik zie wel dat dit een weerslag heeft op de look van “Kort bestek”, maar dat is niet zo erg.
