### ISSUE TITLE
Dossier detail: spacing minister blokken

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#702]
Verbetering van de spacing tussen de delen rond “korte titel”/lange titel/opmerking en de ministers. 

Dit gaat over meer plaats voorzien waar de rode lijn in dit screenshot staat:

![image](https://user-images.githubusercontent.com/12690/108105351-ca7f3a00-708c-11eb-99a4-aff9c80e0014.png)

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#702-fix-agendaitem-titles-spacing

**Comment by brenner-company** [comment]
Even zitten zoeken waardoor de class `auk-u-mb-8` niet correct op element kwam te staan, maar blijkbaar is er bij het omzetten van het component naar een glimmer component niet gelet op het feit dan de `classNames` API niet meer werkt hier en classes binnen de HTML moeten geplaatst worden.

Ik peil sowieso nog eens bij een dev of die `classNames = ['auk-u-mb-8'];` verwijderd mag worden.

Nu, in het algemeen goed om te weten want wie weet hoeveel issues hierdoor al veroorzaakt zijn.

**Comment by Wolfr** [comment]
Ja, right. Goed punt. Dit werkt anders in Ember v2 t.o.v. Ember v3.

**Comment by Wolfr** [comment]
Lijkt me goed.
