### ISSUE TITLE
Styleguide stijlen enkel inladen op styleguide route

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#703]
Styleguide stijlen worden momenteel op productie ingeladen.

```

// Styleguide
@import "custom-application/styleguide/_br-prototype-wrapper";
@import "custom-application/styleguide/_br-styleguide-bordered-list";
@import "custom-application/styleguide/_br-styleguide-bordered-list-header";
@import "custom-application/styleguide/_br-styleguide-code-block";
@import "custom-application/styleguide/_br-styleguide-color-swatch";
@import "custom-application/styleguide/_br-styleguide-color-swatch-list";
@import "custom-application/styleguide/_br-styleguide-columns";
@import "custom-application/styleguide/_br-styleguide-grid-documentation";
@import "custom-application/styleguide/_br-styleguide-icon-list";
@import "custom-application/styleguide/_br-styleguide-sample";
@import "custom-application/styleguide/_br-styleguide-type-sample";
```

Al deze styles moeten in een aparte stylesheet, die enkel wordt ingeladen op dev en op lokale versies. 

Alternatief is enkel inladen op de styleguide route.

**Comment by MikiDi** [comment]
Gewoon conditioneel importen op environment bij het builden lijkt me best. https://guides.emberjs.com/release/addons-and-dependencies/#toc_environment-specific-assets

**Comment by brenner-company** [comment]
Ik laat deze issue even voor wat het is denk ik. Enkele zaken uitgezocht en tot de volgende conclusies gekomen:

- Importen bij het builden (zoals @MikiDi vermeld had) is enkel mogelijk vanuit `node_modules` of `vendor` folder en enkel met al gecompileerde CSS bestanden (geen SCSS).
- Conditioneel importen binnen SCSS via environment variables is spijtig genoeg (nog steeds) niet mogelijk.
- Styleguide CSS kan los van de rest gebuild worden en met de link-tag geinclude worden binnen de algemene template van `aukstyleguide`, maar die link staat binnen de `body` ipv `head` dus weet niet of dat echt goede practice is.
- Mogelijks zou [ember-cli-inline-content](https://github.com/gpoitch/ember-cli-inline-content) of [ember-cli-content-for-index](https://github.com/CondeNast/ember-cli-content-for-index) een oplossing kunnen bieden, maar dan is er vermoedelijk geen garantie dat zaken zoals live-reload nog zouden werken.

Bekijk ik desnoods even de laatste optie of lijkt dat niet de moeite voor wat het is?

**Comment by Wolfr** [comment]
> Styleguide CSS kan los van de rest gebuild worden en met de link-tag geinclude worden binnen de algemene template van aukstyleguide, maar die link staat binnen de body ipv head dus weet niet of dat echt goede practice is.

Deze bullet point optie is volgens mij het beste, ook al is dat iets minder koosjer.

**Comment by Wolfr** [comment]
Besproken: we gaan voor de strategie van de vorige comment.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#703-styleguide-styling-scoped

**Comment by Wolfr** [comment]
Code ziet er goed uit.

**Comment by Wolfr** [comment]
Is dit nu gemerged? Mag dit dicht @brenner-company ?

**Comment by brenner-company** [comment]
Ik moest nog even wachten met mergen tot de vl-refactor op de development branch stond en alles naar acceptatie kon gaan (wat gisterenavond was). Voor de zaken die onder de css-refactor branch zaten (waaronder deze issue) maak ik straks al een PR aan.

**Comment by brenner-company** [comment]
Aanpassingen zijn gemerged. Ik sluit direct deze (en alle andere binnen deze PR) issue.
