### ISSUE TITLE
Spacing utilities nakijken

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#704]
* `.auk-u-mb-10` class weghalen
* Nakijken values (5px based dus de berekeningen moeten kloppen e.g. 3x5)
* Heb ook gemerkt dat er nog iemand een extra utility heeft toegevoegd die zeker ook weg moet (in _spacing.scss)

```
.vlc-u-padding-2 {
  padding: 0.2rem;
}
```

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#704-evaluation-spacing-utilities

**Comment by brenner-company** [comment]
Enkel rond de extra class `.vlc-u-padding-2` zit ik wel nog met een korte vraag. Ik slaag er niet 100% in om het component (waar de class gebruikt wordt) visual te lokaliseren binnen de app en hoe/wanneer die class precies op dat component wordt geplaatst.

**Comment by Wolfr** [comment]
![image](https://user-images.githubusercontent.com/12690/108108021-55156880-7090-11eb-9c75-98cb5fc49b7d.png)

Hier op de + drukken, dan komt er een boxje tevoorschijn.

**Comment by Wolfr** [comment]
De klasse `auk-u-mr-5` wordt gedefinieerd maar nergens gebruikt.

De klasse `auk-u-mr-6` wordt gedefinieerd maar slechts 1 keer gebruikt.

Die laatste wordt gebruikt in een action group, waar algemeen weg van bewogen moet worden (zie ook #723 )

Als we die 2 er nog uit kunnen halen, dat zou goed zijn.

**Comment by brenner-company** [comment]
`auk-u-mr-5` en `auk-u-mr-6` verwijderd binnen lokale kopie van `au-kaleidos-css`. De gebruikte `auk-u-mr-6` vervangen door een legacy spacing class `u-padding--right` om de referentie te kunnen verwijderen. Op zich geen probleem omdat we zo snel als mogelijk willen overschakelen naar de nieuwere toolbar (zoals vermeld binnen #723).

**Comment by brenner-company** [comment]
- Lokale kopie van `au-kaleidos-css` is terug verwijderd en aanpassingen zijn doorgevoerd binnen de eigenlijke package.
- `au-kaleidos-css` package is geupdate en naar versie `1.19.0` gebracht.
- SCSS import opnieuw naar package binnen `node_modules` laten verwijzen.

**Comment by brenner-company** [comment]
Todo na merge naar `development`:
- Bericht plaatsen binnen kanselarij-dev channel om andere devs op de hoogte te brengen.
- Release aanmaken binnen https://github.com/kanselarij-vlaanderen/au-kaleidos-css/releases
