### ISSUE TITLE
Centreren van loader

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#708]
Momenteel komt er op veel plekken een loader tevoorschijn.

![image](https://user-images.githubusercontent.com/12690/108105013-58a6f080-708c-11eb-8a94-9cf779e6aced.png)

Deze staat nu te plakken tegen de bovenkant, maar moet gecentreerd worden in het vlak.

Design link: https://www.figma.com/file/TV7uHiWOymlNTZnD1DGMiE/%F0%9F%92%AF-Kaleidos-Grooming-Digitale-Publicaties?node-id=1280%3A19281

**Comment by brenner-company** [comment]
Voor het design mis ik blijkbaar nog de nodige rechten, check je dat even na als je de tijd hebt?

![image](https://user-images.githubusercontent.com/18174827/108250636-c6b7ea00-7156-11eb-9ffb-706c4fc404a7.png)

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#708-center-loading-animation

**Comment by brenner-company** [comment]
Een manier gevonden om alle loaders goed te krijgen zonder al te veel aanpassingen binnen de specifieke pagina's te moeten doen.

Ik heb zoveel mogelijk locaties van de loaders opgezocht en visueel afgechecked, maar er is wel een kans dat ik er één gemist zal hebben. Mochten er toch nog zijn die niet aan vereisten van deze issue voldoen, plaats gerust hier een comment.

**Comment by Wolfr** [comment]
Cool!

**Comment by Wolfr** [comment]
Lijkt me goed. Super.
