### ISSUE TITLE
Dossier detail: success pill mag een gewone pill worden

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#709]
![image](https://user-images.githubusercontent.com/12690/108105469-f26e9d80-708c-11eb-9336-903a48458780.png)

De “success” pill mag een gewone pill worden op dit stukje.

**Comment by Wolfr** [comment]
Je zou daar de nieuwere pill kunnen gebruiken, zie http://localhost:4200/aukstyleguide/pill

Diegene die het moet zijn is de default pill.

![image](https://user-images.githubusercontent.com/12690/108105771-51341700-708d-11eb-89a3-15a561e94810.png)

**Comment by brenner-company** [comment]
Aangepast, maar toch even om af te checken:
- Er moet niet meer gekeken worden naar een success state (want binnen de code maakten ze daar onderscheid tussen)?
- Bij de oude code voorzagen ze nog een `vl-u-text--capitalize` om waarschijnlijk labels zonder hoofdletter op te vangen. Mag ik een alternatief hiervoor voorzien binnen `au-kaleidos-css`?
- Mogen de pills daaronder (default + success) ook vervangen worden?

![image](https://user-images.githubusercontent.com/18174827/108233890-80f22600-7144-11eb-8ea3-9fc5cbd6883c.png)

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#709-replace-pill

**Comment by Wolfr** [comment]
* Die success state, dat is nooit zo ontworpen voor zover ik weet, dat is er ingeslopen op dev.
* Capitalizen via CSS zou ik vermijden
* De pills daaronder zou ik ff afblijven tot ik de code heb nagekeken

**Comment by Wolfr** [comment]
Op dit scherm is er blijkbaar beginnen gewerkt worden in #740 .

Ik vraag hier al maanden naar en had niet verwacht dat dit nu net op de sprint zou landen.

Dit is dezelfde change op 2 plekken, dus misschien kunnen we deze “annuleren” aangezien deze change al gebeurd is in @brechtPhilips  zijn branch.

**Comment by brechtPhilips** [comment]
De rework staat in branch KAS-2142, deze is nog niet optimaal ik heb me gebaseerd op de huidige designs. Er staat nog inline css in deze zou nog naar een andere file moeten.

**Comment by brenner-company** [comment]
Na merge van `development` naar `DES/enhancement/css-refactor` staat de pill nog steeds in zijn juiste vorm. Ik sluit deze issue af (omdat er nu niets te mergen valt).
