### ISSUE TITLE
De tabs bovenaan in Agenda's staan te ver uit elkaar

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#711]
De tabs bovenaan in Agenda's staan te ver uit elkaar

![image](https://user-images.githubusercontent.com/12690/108105933-8e000e00-708d-11eb-9b4c-f7b662da78b6.png)

In het design staan deze dichter.

Voorbeeld 

![image](https://user-images.githubusercontent.com/12690/108105982-a2440b00-708d-11eb-83b4-f2b29091082d.png)

https://www.figma.com/file/cRQyjDA19dlGXvTDTUhoE4/%F0%9F%92%AF-Kaleidos-Q1-2021-mockups-Alle?node-id=14%3A4877

**Comment by brenner-company** [comment]
@Wolfr: binnen de bestaande code zie ik dat de tabs via `.vlc-tabs-reverse` geïmplementeerd worden. Nu, de meest logische optie zou zijn om dit te vervangen door een `WebComponents::AuTabs`, maar ik heb geen idee of dat mogelijk is aangezien de huidige tabs een mix zijn van reguliere routes & actions.

Wat zou dan beste optie zijn?
- Bestaande code vervangen door HTML structuur van `WebComponents::AuTabs`?
- CSS van bestaande structuur (`.vlc-tabs-reverse`, etc.) aanpassen?

**Comment by Wolfr** [comment]
Gewoon de extra padding eruit zwieren for now.

Deze regel aan te passen, dat het er visueel meer uit ziet zoals de designs:

```  padding: 0.7rem 4rem 0.8rem;```

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#711-vlc-reverse-tabs-spacing
