### ISSUE TITLE
Inconsistent BEM gebruik _vlc-case.scss

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#712]
Ik kwam deze code tegen in `_vlc-case.scss`:

```
.vlc-case-description__grid {
  display: grid;
  grid-template-columns: 30% 30% 30%;
  grid-gap: 10%;
}
```

Dit is een BEM child, maar er is geen parent.

De CSS file heet ook niet zoals de component, zoals we proberen te doen.

Dit is een kleine refactor om conform te zijn.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#712-inconsistent-bem
