### ISSUE TITLE
Numac number list

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#716]
I saw this come by in a commit.

https://github.com/kanselarij-vlaanderen/kaleidos-frontend/blob/b6311277d663b30ba59829c3a9a8dbadf779d733/app/styles/custom-components/_vlc-numac-nummer-list.scss

This file needs fixes to accord to coding standards. Just posting this here for a review meeting with @brenner-company .

**Comment by brenner-company** [comment]
Nu ik zie waar deze CSS gebruikt wordt herinner ik me dat dit vermeld is geweest binnen de demo op 17/02. Deze moest functioneel werken, maar had inderdaad nog op visueel vlak redelijk wat werk nodig (zie screenshot).

Verder is er ook wel een verschil met wat er binnen de designs staat? De eerste referentie die ik naar daar kan vinden is [deze](https://www.figma.com/file/TV7uHiWOymlNTZnD1DGMiE/%F0%9F%92%AF-Kaleidos-Grooming-Dev?node-id=1152%3A18043).

Laat ik deze nog even liggen en bespreken we dit begin volgende week nog eens opnieuw? Nu opnieuw uitwerken naar BEM standaarden lijkt me nogal overbodig werk.

![image](https://user-images.githubusercontent.com/18174827/108515237-22a08100-72c5-11eb-930b-77f5f2fd5a00.png)

**Comment by Wolfr** [comment]
![image](https://user-images.githubusercontent.com/12690/108892148-d5e3df80-760f-11eb-9593-c12271728755.png)

Ik snap niet goed waarom deze multi select zo geïmplementeerd is, met 2 inputs en een toevoegen knop (link).

Op dev bv. hier https://kaleidos-dev.vlaanderen.be/publicaties/602E178CE0D77A0008000001/dossiers staan nog  allerhande inline stijlen. 

We zullen het eens checken in onze meeting.

**Comment by Wolfr** [comment]
Kadert in algemene kwaliteit componenten; power select e.d.; nieuwe issue voor aan te maken.
