### ISSUE TITLE
Cypress testen

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#717]
Uitzoeken hoe Karel Cypress testen kan runnen.

**Comment by brenner-company** [comment]
De instructies binnen de readme's van `kaleidos-project` en `kaleidos-frontend` kunnen volgen, maar blijkbaar moet er nog iets gecorrigeerd worden mbt mijn configuratie ervan.

Ik wacht dus nog even tot ik een dev vast kan krijgen om het proces te doorlopen.

**Comment by brenner-company** [comment]
Hulp van @ValenberghsSven gehad hierbij 👏
