### ISSUE TITLE
Icons npm warn

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#718]
`npm WARN The package @kanselarij-vlaanderen/au-kaleidos-icons is included as both a dev and production dependency.`

**Comment by MikiDi** [comment]
Zie comment hier https://github.com/kanselarij-vlaanderen/kaleidos-frontend/pull/600#discussion_r539089926 voor toelichting.

**Comment by MikiDi** [comment]
Fixed in 3f3642757e91751cb9c35c5b16d7f4ec32c0734a
