### ISSUE TITLE
Mock login route: bovenkant met missing image

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#719]
![image](https://user-images.githubusercontent.com/12690/108253286-e866a080-7159-11eb-8671-7eb9a09a1d6b.png)

Op de mock login route, mag die bovenkant helemaal weg.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#719-remove-mock-login-header
