### ISSUE TITLE
Hover state data table

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#721]
![image](https://user-images.githubusercontent.com/12690/108255147-295fb480-715c-11eb-8c9c-8305d137284d.png)

De hover state op een data table heeft niet de juiste kleur, het is geen blauwgrijs maar een gewoon grijs.

Een andere familie grijzen dus. We zouden dit component kunnen moderniseren naar de nieuwe kleuren.

**Comment by emilyvandewalle** [comment]
https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/WU3-Kaleidos-Master-Library-Design-patterns?node-id=2385%3A3508

**Comment by Wolfr** [comment]
@brenner-company De juiste kleur is nu gedocumenteerd voor zebra en non-zebra tables in de Figma link hierboven ☝️ . Dit kan geïmplementeerd worden.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#721-table-row-hover-styling
