### ISSUE TITLE
Mini spacing tussen agenda items mag weg

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#722]
![image](https://user-images.githubusercontent.com/12690/108255269-557b3580-715c-11eb-9954-fa5d12b11307.png)

Tussen items in de lijst van een agenda staat zo een klein plekje. Maar daar is geen reden voor, en niet conform designs. Dit mag weg.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#722-remove-inbetween-spacing

**Comment by brenner-company** [comment]
Daarnaast lijkt het me ook interessant om te kijken of die `.vlc-agenda-items--spaced` niet uit de code kan gehaald worden, maar staat dan eerder onderaan op de lijst met prioriteiten.
