### ISSUE TITLE
“Naar procedurestap” link op agenda detail

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#723]
![image](https://user-images.githubusercontent.com/12690/108255519-aab74700-715c-11eb-9860-1fe0d1943621.png)

We kunnen “naar procedurestap” op agenda detail bovenaan zetten, naast de 2 knoppen uitstellen en verwijderen.

Momenteel staan de 2 knoppen in een `.vl-action-group`. 

Dit kan vervangen worden door een `auk-toolbar`. 

Zie de documentatie van een toolbar: http://localhost:4200/aukstyleguide/toolbar

De oude documentatie van action group voor een beetje context: https://overheid.vlaanderen.be/webuniversum/v3/documentation/components/vl-ui-action-group/

**Comment by MikiDi** [comment]
Zie ook @brechtPhilips 's werk op https://github.com/kanselarij-vlaanderen/kaleidos-frontend/pull/740

**Comment by Wolfr** [comment]
Aha! Goed dat hier aan begonnen is.

**Comment by Wolfr** [comment]
Deze issue vervalt dan eigenlijk.
