### ISSUE TITLE
Grijze box gebruiken in edit state van de Nota

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#724]
![image](https://user-images.githubusercontent.com/12690/108255962-34ffab00-715d-11eb-8c00-fb46f81d55aa.png)

Als je een nota wijzigt, staat dit niet in een box. Dit moet wel naar een box.

Dit is een eerste stap richting het correct implementeren van de panel layout.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#724-edit-state-box
