### ISSUE TITLE
Icoontje zoekpagina

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#725]
![image](https://user-images.githubusercontent.com/12690/108256298-a50e3100-715d-11eb-8328-67f2c0479d78.png)

Op de zoekenpagina is het icoontje bij trefwoord niet goed uitgelijnd.

Het moet ook grijzer zijn.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#725-search-icon

**Comment by brenner-company** [comment]
Naast de aanpassingen binnen structuur heb `.auk-icon--muted` als class gebruikt om icon een meer passende grijswaarde te geven. Deze komt niet 100% overeen met de grijswaarde van de gedateerde `.vl-form__label`, maar dan is al in orde wanneer de labels aangepast worden naar `WebComponents::AuLabel` componenten.

Ik wou dat laatste nu al direct in orde brengen (zodat de grijswaarden overeen komen), maar met één iets aan te passen open ik blijkbaar pandora's box voor andere issues, dus hier wacht ik even mee tot ik aan de refactor begin.
