### ISSUE TITLE
Popup zoekpagina

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#726]
![image](https://user-images.githubusercontent.com/12690/108256496-e7d00900-715d-11eb-9710-b42a646e4efe.png)

Je kan hier geraken door op http://localhost:4200/zoeken/agendapunten te klikken op het info icoontje bij trefwoord.

In de popup van de zoekpagina staat er een tabel kolom te veel.

Ook zou de laatste lijn niet zichtbaar moeten zijn.

**Comment by Wolfr** [comment]
In het prototype ziet die popup er al beter uit.

<img src="https://user-images.githubusercontent.com/12690/108369793-3fbd4d00-71fc-11eb-88f6-2b98113e8414.png" width="450">

Kunnen we de code van het prototype naar de front-end brengen?

https://kaleidos.mono.global/app/search/agendapunten

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#726-searchpage-popover

**Comment by brenner-company** [comment]
@Wolfr Ik mis enkel nog een entry binnen `nl-be.json` voor 'Hulp bij zoeken'. Is dit iets wat ik zelf zou mogen toevoegen binnen die file? (desnoods vraag ik het eens aan iemand van de devs)

**Comment by Wolfr** [comment]
Ja, labels mag je gewoon zelf toevoegen.

**Comment by brenner-company** [comment]
Momenteel wordt de popover nog getoond via een `AttachPopover`, maar binnen de prototypes van Mono zie ik dat er eerder voor een `EmberPopover` wordt gegaan. Komt er nog een specifiek popover component binnen app of kijk om tijdens #732 om gelijk te trekken met het prototype?

**Comment by Wolfr** [comment]
Ik heb hier geen kennis over. Wat ik wel weet is dat we een zo modern mogelijke versie van Popper willen gebruiken (De 2.x branch op https://popper.js.org/docs/v2/ )
