### ISSUE TITLE
Handtekeningen beheren

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#728]
Ik kwam de module “handtekeningen beheren” tegen in de instellingen.

Wordt dit nog gebruikt? Ik heb dit nog nooit in actie gezien en weet niet waar het voor dient.

Algemene vraag, op te nemen met dev team (gebundeld) - niet voor @brenner-company .

**Comment by MikiDi** [comment]
Dit maakt volgens mij deel uit van een feature die nooit volledig in gebruik genomen is / niet gebruikt wordt (om de secretaris z'n handtekening te tonen onderaan de printable lijst van beslissingen). Hoogstwaarchijnlijk helemaal eruit te strippen alvorens die feature opnieuw te analyseren.

**Comment by Wolfr** [comment]
Tangentially related - Er is nu een feature idee rond signatures voor de mails van OVRB, maar die setting zou op gebruikersniveau leven.

**Comment by Wolfr** [comment]
Dit zou eigenlijk in Jira moeten gelogd worden als refactor issue, om eruit te halen, om de codenbase behapbaarder te maken.

@erikap

**Comment by Wolfr** [comment]
Closed want gelogd op Jira https://kanselarij.atlassian.net/browse/KAS-2492
