### ISSUE TITLE
Nota wijzigen in context van een dossier

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#730]
![image](https://user-images.githubusercontent.com/12690/108257814-9de82280-715f-11eb-961a-dc1bcd78735a.png)

Als je in een dossier een nota wijzigt, dan plakt dit tegen de ministers & beleidsvelden wijzigen.

To do: ervoor zorgen dat dit niet meer het geval is.

To reproduce:

1. Ga naar een dossier http://localhost:4200/dossiers/602D6D46E0D77A000800002D/deeldossiers/602D6FB1E0D77A0008000036/overzicht
2. Klik op “wijzigen” bij de nota

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#730-fix-subcase-context-spacing
