### ISSUE TITLE
Wat is Ember truth helpers?

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#731]
Vrij obscure projectkennis maar toch ook belangrijk om te weten.

Ember truth helpers is een externe package om te helpen met conditional logica. Scan even de README:

https://github.com/jmurphyau/ember-truth-helpers

Als je dus code genre dit tegenkomt:

	{{if (eq a b)}}

Dan is het powered door die truth helpers. Dit komt voor in de Handlebars view templates, en in de Handlebars templates voor de componenten.

**Comment by brenner-company** [comment]
Bedankt voor de extra info. Die `{{if (eq a b)}}` had ik voordien al even tegen gekomen en in die context had ik wel snel door wat dit effectief deed, maar de bijkomende vormen zijn wel interessant geweest om even te overlopen.
