### ISSUE TITLE
Code refactor: algemeen idee - beginnen bij de kleinste componenten

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#733]
`<i class="vl-link__icon vl-link__icon--before vl-toggle__icon ki-chevron-right"></i>`

Dit soort code verwijst naar een icoontje, met de oude logica.

De nieuwe logica is een component gebruiken:

`<WebComponents::AuIcon @name="chevron-right" />`

Wanneer we het in het verleden hebben gehad over beginnen refactoren, dan ging het over van het kleinste element naar het grootste.

Dus ipv. te beginnen met wrappers en dergelijke te gaan bekijken, beginnen met de atoms consistenter te trekken. Zoals de issue rond de pill ( #709 ).

Hierdoor wordt de code veel voorspelbaarder, en kunnen we zaken beginnen strippen.

**Comment by brenner-company** [comment]
Omdat https://github.com/kanselarij-vlaanderen/kaleidos-frontend/issues/802 hier ook qua onderwerp bij aansluit wordt deze issue afgesloten en alles verder daar opgevolgd.
