### ISSUE TITLE
Ordening CSS - 1-malige componenten andere naam

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#735]
Nog een idee dat ik had.

1 malige (vaak layoutmatige) componenten moeten een andere prefix krijgen.

Je hebt de objects in ITCSS, soms gebruik ik `l-` voor layout.

Zo is het duidelijk dat ze iets anders zijn dan een herhaalbaar element zoals een button of een pill.

Dit is ook belangrijk in een breder design system verhaal om het verschil te maken tussen wat lokaal tot het project behoort of behoort tot een bredere groep componenten.

**Comment by brenner-company** [comment]
Binnen de vlc-refactor een ideale kandidaat hiervoor gevonden: namelijk `.vlc-toolbar--slide-in` (extra styling op toolbar binnen main header) binnen de (ondertussen verwijderde) `_vlc-toolbar.scss`.

Het resultaat: https://github.com/kanselarij-vlaanderen/kaleidos-frontend/commit/cdfa8d3e7d0cc50f88fe27968dcf9511e5470ce8

Enkel nog niet letten op de locatie en de benaming van dat bestand (dat moet ik ook nog eens afchecken met je), maar is dit wat de richting die we hiermee uit willen, @Wolfr?

**Comment by brenner-company** [comment]
Dit ticket is ofwel afgerond of niet meer van toepassing en mag afgesloten worden.
