### ISSUE TITLE
Hover state document badge/list

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#737]
![image](https://user-images.githubusercontent.com/12690/108367608-eb18d280-71f9-11eb-8de7-aa5fa3063ab1.png)

Die hover state op zo'n document, dat is nooit zo de bedoeling geweest, dat is er ergens in dev ingesukkeld.

We moeten eens bekijken hoe dit er dan wel zou moeten uitzien. Maar alleszins niet zo.

**Comment by Wolfr** [comment]
Op het huidige prototype is er geen rekening mee gehouden dat dit een link kan zijn, dus dat is het ook niet helemaal: https://kaleidos.mono.global/app/agendas/overview

**Comment by brenner-company** [comment]
@Wolfr: ik heb het label 'design-clarity-needed' hier aan toegevoegd. Voor future reference, is dit correct?

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2919
