### ISSUE TITLE
Affordance inline editing document widget

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#738]
Het document widget heeft een affordance probleem.

Dit kunnen we hotfixen in afwachting van een beter document widget.

Ik leg nog duidelijker uit waar dit over gaat.

* Pijltjes
* Hover states

**Comment by emilyvandewalle** [comment]
Design pattern inline editing affordance:
https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/WU3-Kaleidos-Master-Library-Design-patterns?node-id=2388%3A2884

**Comment by Wolfr** [comment]
Niet alles is even rechtstreeks implementeerbaar.

@emilyvandewalle Ik heb nog wat design comments gezet.

@brenner-company we zullen hier doorgaan in onze meeting en ik kan aanduiden wat we voorlopig wel kunnen doen.

**Comment by Wolfr** [comment]
@brenner-company dit mag je voorlopig negeren, we moeten hier nog verder werken op het design.

**Comment by Wolfr** [comment]
Ik denk dat we eerder voor het nieuwe document widget gaan gaan met een feature flag ipv het oude te verbeteren met usability fixes, maar dat is nog in bespreking.

**Comment by brenner-company** [comment]
Dit ticket is ofwel afgerond of niet meer van toepassing en mag afgesloten worden.
