### ISSUE TITLE
Tests tabel breedtes

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#739]
Hoe kunnen we de breedtes van tabellen beter controleren door CSS klasses? Tests te maken om erna toe te passen op publicatie hoofd tabel.

**Comment by Wolfr** [comment]
Dit gaat vooral over het optimaliseren van de view van de grote tabel bij publicaties.

Te zien op https://kaleidos-dev.vlaanderen.be/publicaties

![image](https://user-images.githubusercontent.com/12690/108903510-ab008800-761d-11eb-9391-07abea1c83e4.png)

We moeten dit aanpakken op verschillende manieren:

* Op componentniveau - niets moet breder zijn dan het eigenlijk moet zijn
  * Ik zie bv. dat de counter badges niet kloppen
* Correct wrappen van bepaalde cellen
* Op tabelstijl niveau: de padding en whitespace tweaken 
* Op labelniveau: werken met kortere labels (dit is reeds gelogd in Jira)

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2920
