### ISSUE TITLE
Publicaties: counter documenten

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#744]
![image](https://user-images.githubusercontent.com/12690/108422184-82038000-7236-11eb-948b-bc0ffb400b8f.png)

er staat te veel plaats tussen het aantal documenten en het label.

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2900
