### ISSUE TITLE
Multi select stijlen

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#748]
<img src="https://user-images.githubusercontent.com/12690/108423543-45d11f00-7238-11eb-94f7-28a08fea8042.png" width="300">

De multi select kan beter gestijld worden conform design.

Te vinden bij het toevoegen van een organisatie bij een contactpersoon.

Eventueel te documenteren in de styleguide?

**Comment by emilyvandewalle** [comment]
https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/WU3-Kaleidos-Master-Library-Design-patterns?node-id=2385%3A2938

**Comment by Wolfr** [comment]
#803 related

**Comment by Wolfr** [comment]
We zijn nog bezig met design clarity krijgen hier.

**Comment by Wolfr** [comment]
Dit is ondertussen duidelijker, zoals besproken in meeting.

https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/WU3-Kaleidos-Master-Library-Design-patterns?node-id=2955%3A9

<img width="607" alt="CleanShot 2021-04-23 at 09 56 01@2x" src="https://user-images.githubusercontent.com/12690/115846651-6c6f2a00-a422-11eb-85be-d461a4e50ac1.png">

We kunnen de power select bijstijlen zodat dit meer lijkt op wat het moet zijn.

Heb de vraag rond resultaten zien in https://appuniversum.github.io/ember-appuniversum/docs/atoms/ember-power-select gesteld op #appuniversum kanaal.

**Comment by brenner-company** [comment]
Issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2915
