### ISSUE TITLE
Icons: update to a new package 

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#757]
In reference to https://github.com/kanselarij-vlaanderen/au-kaleidos-icons/issues/2 we could look at the icons.

This process will involve first creating a new package which fixes the doubles, remove the legacy icons, release a new version, and then make sure we use this new version on the Kaleidos front-end.

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2921
