### ISSUE TITLE
Labels Ministerraad

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#760]
```
  "via-cabinet": "Via Ministerraad",
  "not-via-cabinet": "Niet via Ministerraad",
```

Ik zou dit toch eerder vertalen als “Ministerial Council” om geen verwarring te krijgen met de kabinettenwerking.

Bug nog te verzetten naar Jira, geen CSS bug

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2922
