### ISSUE TITLE
Oude styleguide verwijderen

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#763]
De styleguide op `/styleguide` mag verwijderd worden.

**Comment by Wolfr** [comment]
@brenner-company Dit zou ik toch wel eens willen doen. Dit lijkt me een aparte PR.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#763-#764-#767-styleguide-final-state
