### ISSUE TITLE
Nieuwe versie AU CSS maken

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#766]
* https://github.com/kanselarij-vlaanderen/au-kaleidos-css - nieuwe versie maken met minor version number (bv. 1.19, 1.20)
* Erna dient die toegepast te worden op de echte front-end
* Op basis van recente changes

**Comment by brenner-company** [comment]
Aanpassingen zijn doorgevoerd en gedocumenteerd binnen #704.
