### ISSUE TITLE
De scrollbar in de styleguide staat verkeerd

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#767]
![image](https://user-images.githubusercontent.com/12690/109159099-82d76d00-7774-11eb-992a-57b521ee3aeb.png)

**Comment by brenner-company** [comment]
@Wolfr: Om verder in te gaan op mijn vraag en ons kort gesprek op Slack:

> Ik zie dat er via Ember addons (specifiek `node_modules/@lblod/ember-vo-webuniversum`) al een aantal `.br-styleguide-…` styles mee in de `vendor.css` gebuild worden.
>
> Nu, die hebben dezelfde namespace als de styles die nodig zijn om de styleguide vorm te geven en geven wat conflicten (daarmee dus de scrollbalk op de verkeerde locatie).
>
> Is het de bedoeling dat die `.br-styleguide-…`  classes elkaar complimenteren en voorzie ik aantal overrides? Of is dat niet de bedoeling en geeft ik die styleguide styles (binnen Kaleidos front-end zelf) bv. een andere namespace?

\+

> Ik vermoed dat de CSS automatisch mee geinclude wordt omdat die package ooit via een `ember install` binnen het project is gehaald?
>
> Styling zelf (die de issue veroorzaakt) komt uit `node_modules/@lblod/ember-vo-webuniversum/vendor/lblod/prototype.css` (regel 524)

Voor de issue zelf heb ik gewoon even kleine override voorzien (`width: 100%`), maar er zou dus nog eens gekeken moeten worden wat er gedaan kan worden mbt de oorzaak van de issue.

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/#763-#764-#767-styleguide-final-state

**Comment by Wolfr** [comment]
Deze repo lijkt WebUniversum in zijn geheel te tonen.

![image](https://user-images.githubusercontent.com/12690/113139491-7ccb2500-9227-11eb-84d4-0bef498f56b7.png)

Ik weet niet goed hoe dat zo gebeurd is, maar ik heb een PR gedaan op die module om die files weg te halen.

https://github.com/lblod/ember-vo-webuniversum/pull/3

Ik snap niet goed waarom dit een dependency is van ons project. 1 theorie die ik had dat we op die manier misschien de Javascript files van WebUniversum inladen. Maar ik zie deze niet staan.

Ik denk dat we dus in zijn geheel de dependency mogen weghalen in onze repo.
