### ISSUE TITLE
auk key value

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#769]
![image](https://user-images.githubusercontent.com/12690/109161427-54a75c80-7777-11eb-967f-3ba23ece0f2b.png)

* Afraden om dit component zo te gebruiken
* Eerder de divs gebruiken als wrappers
* anders te veel prop passing hell

**Comment by Wolfr** [comment]
Concrete todo is dus de documentatie aan te passen naar divs en straight-up HTML code ipv de expliciete component.

We kunnen de Octane component zelfs verwijderen. (maar de CSS en HTML moet blijven bestaan)

**Comment by Wolfr** [comment]
Ik heb recent geleerd dat de parent van een definition list item ook een div mag zijn
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#wrapping_name-value_groups_in_htmlelementdiv_elements

Dit is eigenlijk een soort definition list, dus dat kunnen we toepassen.

**Comment by brenner-company** [comment]
Binnen #732 zijn de vlc-instanties al omgezet naar de correcte description list structuur. Vanaf het moment dat ik de bestaande auk-variant in component vorm (gedaan binnen vl-refactor) naar HTML/CSS omzet zal ik deze issue als referentie gebruiken.

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2918
