### ISSUE TITLE
Mock login

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#786]
Mock login pagina kan betere styling gebruiken, cfr. prototype: http://development.kaleidos-prototype.mono.digital/authentication/overview.html

**Comment by Wolfr** [comment]
Eerst gaan we een algemeen list component maken, en dit hier op toepassen.

**Comment by Wolfr** [comment]
We hebben hier nu wel een nieuw design voor, maar enige opmerkingen op het bestaande mock-login scherm wereden eerder koud onthaald, dus ik stel voor hier voorlopig niet aan te werken.

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2923
