### ISSUE TITLE
Acties op agenda

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#787]
Weet niet goed wat er hier gebeurd is, maar deze acties dienen zeker niet gecentreerd te zijn.

Ook staat er een divider te veel denk ik: je zou eerst de 2 blauwe acties moeten krijgen, dan een divider, en dan de verwijder actie. 

![image](https://user-images.githubusercontent.com/12690/113141024-776eda00-9229-11eb-8961-30e49f722346.png)

Knop rechtsboven op het overzicht van een agenda.

**Comment by MikiDi** [comment]
Omtrent de divider was recent wat talk, hier in de buurt https://kanselarij.atlassian.net/browse/KAS-2214?focusedCommentId=15266 ... @ValenberghsSven zal meer weten.
