### ISSUE TITLE
Agendapunten synchroniseren tussen prototype en front-end

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#788]
Algemeen doel: nieuwe CSS component gebruiken voor agendapunten.

Agendapunten heeft vrij specifieke en grote code, met veel hoekjes en kantjes.

Maar we moeten er wel eens werk van maken om dit te updaten naar een nieuwe versie.

Dit is groot genoeg om uiteindelijk een dedicated Jira ticket te worden en mee te nemen op sprintplanning, ik begin hier alvast een deel van de uitleg.

Hier gaan we goed op moeten samen werken (met bv. Fanny en Michaël) 

### Wat mist er nog in prototype?

* Volgorde controls - Zie https://github.com/mono-company/kaleidos-prototype-v3/issues/87 
* Documenten zijn clickable en gaan naar modal van document  https://github.com/mono-company/kaleidos-prototype-v3/issues/88

#### Styling icoontjes agendapunten

![image](https://user-images.githubusercontent.com/12690/113141264-c583dd80-9229-11eb-91ec-3a9b3743a953.png)

Styling icoontjes agendapunten rechtsonder: dit ziet er niet zo goed uit.

Referentie naar component in prototype: http://development.kaleidos-prototype.mono.digital/styleguide/auk-agenda-items.html#component-02-auk-agenda-items-extensive

Deze nieuwe component gebruikt denk ik totaal andere CSS, dus gaat wel een werkje zijn om dit goed te krijgen.

#### Icoontjes documenten

![image](https://user-images.githubusercontent.com/12690/113141835-81450d00-922a-11eb-9481-ab38a59d87b6.png)

Er worden oude icoontjes gebruikt, die outdated zijn. Ik maak een apart issue aan voor de iconen te updaten.

#### Functioneel

Vertrouwelijk 

### Waar moeten we zeker rekening mee houden?

Je kan deze view ook printen.

**Comment by MikiDi** [comment]
In deze component zijn "under the hood" recent heel wat veranderingen geweest: best checken of https://github.com/kanselarij-vlaanderen/kaleidos-frontend/pull/778 op de `development` branch zit alvorens hieraan te beginnen.  
Alvast een tip vanuit dev-perspectief: de data achter het "oogje" ("niet zichtbaar in kort-bestek") is een side-loaded data-element. Omdat het oogje enkel in 1 van de 2 mogelijke states getoond wordt, kan er verwarring optreden omtrent de effectieve waarde indien deze data nog "loading" is. Voor dit specifieke element was vanuit de gebruikers vraag naar een ui loading-state voor het oogje.

**Comment by Wolfr** [comment]
Dank voor de info @MikiDi . Voor we hier effectief aan beginnen moeten we hier samen naar kijken en zien waar we nog allemaal rekening mee moeten houden etc. Dit is een vrij ingewikkelde.

**Comment by MikiDi** [comment]
Wat betreft het printen, for reference: momenteel is er een aparte route voorzien voor het printen van het agenda op bv https://kaleidos-dev.vlaanderen.be/vergadering/5EDE149C4A2F330008000018/agenda/e64f4e80-d011-11ea-a5bd-d71b3933dfd7/afdrukken (agenda: "acties" > "afdrukbare versie"). Deze komt wat maintenance tekort, maar is al dicht bij wat de gebruikers qua lay-out verwachten (redelijk specifieke specs). Zie ook https://kanselarij.atlassian.net/browse/KAS-1992

**Comment by brenner-company** [comment]
Dit ticket is ofwel afgerond of niet meer van toepassing en mag afgesloten worden.
