### ISSUE TITLE
Iconen package updaten

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#789]
Er zou een updated versie moeten gemaakt worden van de iconen package, in het prototype zijn heel wat nieuwe iconen toegevoegd, er zijn iconen van naam veranderd en er zijn ook iconen verwijderd. 

Related info: https://github.com/mono-company/kaleidos-prototype-v3/issues/75
https://github.com/mono-company/kaleidos-prototype-v3/issues/28

Ik zou een kopie maken van de SVGs van het prototype en vergelijken met de SVGs op https://github.com/kanselarij-vlaanderen/au-kaleidos-icons . Dan een oplijsting maken van wat er allemaal veranderd is in de changelog; en een nieuwe release maken.

**Comment by Wolfr** [comment]
Marked als `important` omdat veel werk hiervan af hangt.

**Comment by brenner-company** [comment]
Om de changes iets makkelijker te visualiseren even een export gedaan van de verschillen op file niveau (tussen `au-kaleidos-icons/svg` en `kaleidos-prototype-v3/content/icon-font-source`): [#789-icon-sync.pdf](https://github.com/kanselarij-vlaanderen/kaleidos-frontend/files/6285014/789-icon-sync.pdf)

@Wolfr: wat ik zelf nog zou moeten uitklaren (en daar kan jij wel mee even kort helpen vermoed ik), is om volgende lijst correct te krijgen:

(links is `au-kaleidos-icons`-versie, rechts die van `kaleidos-prototype-v3`)

- [x] `arrow-###.svg` -> `caret-###.svg` (komt enkel maar voor binnen een table component)
- [x] `back.svg` -> `hierarchical-back.svg`
- [x] `calendar-plus.svg` -> `calendar-new.svg`
- [x] `circle-close.svg` -> `circle-error.svg`
- [x] `circle-pause.svg`
- [x] `circle-more.svg`
- [x] `document-updated.svg` -> `document-added.svg`
- [x] `drag-handle-18.svg` -> `drag-handle.svg`
- [x] `hide.svg` -> `not-visible.svg`
- [x] `plus.svg` -> `add.svg`

![CleanShot 2021-04-12 at 11 36 57](https://user-images.githubusercontent.com/18174827/114374130-9b181580-9b83-11eb-9ef9-2f0d45172a5e.png)

**Comment by brenner-company** [comment]
Volgende iconen zouden ook hun kleur 'verliezen' met de sync:

- `circle-close.svg`
- `document-added.svg`
- `lightbulb.svg`
- `mail.svg`
- `plus.svg`
- `timeline.svg`

Zorg ik er dan na de sync er voor dat die iconen (of hun vervangers) nog steeds dezelfde kleur hebben?

**Comment by Wolfr** [comment]
Die kleur moet eigenlijk geregeld worden door de CSS. Alle icons zouden gewoon zwart moeten zijn.

Ik denk niet dat het veel uitmaakt momenteel. Doe maar gewoon en we lossen het wel op als er iets breekt.

**Comment by brenner-company** [comment]
Package is geupdate met een 'minor release', classnames zijn waar nodig aangepast of vervangen en er zijn daar rond ook enkele zaken in orde gebracht binnen de styleguide.

Aanpassingen op de volgende branch: DES/enhancement/#789-icon-sync

Even door de app gegaan en zie geen issues buiten dan de volgende (die ik al eens vermeld had - geen alternatief voor pauze icon):

![CleanShot 2021-04-12 at 16 13 25](https://user-images.githubusercontent.com/18174827/114423932-f3690a80-9bb7-11eb-8d1a-273e015f2724.png)

@Wolfr: maak ik daarvoor al een PR aan of wil je die zelf nog eens doorlopen?

**Comment by Wolfr** [comment]
https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/WU3-Kaleidos-Master-Library-Design-patterns?node-id=1%3A300

Het `circle-pause` icoon bestaat?

**Comment by brenner-company** [comment]
Met dat dit icoon (+ `circle-more`) niet binnen het prototype bestond, maar wel binnen `au-kaleidos-icon` was ik niet 100% zeker of deze mee moesten. Ik check morgenochtend eens of de versie binnen `au-kaleidos-icon` correct is en pas deze aan binnen de templates.

**Comment by Wolfr** [comment]
Hmm, dan moeten we het prototype ook eens updaten zodat het daar ook klopt. Ik log een issue.
