### ISSUE TITLE
Alert stack pagina styleguide

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#791]
![image](https://user-images.githubusercontent.com/12690/113143254-375d2680-922c-11eb-963c-410a70661228.png)

Hoe het hier staat, is geen goed voorbeeld, met die “Annuleren” knop.

Er is een related issue in het prototype https://github.com/mono-company/kaleidos-prototype-v3/issues/80 . Mss eerst de afwerking daarvan afwachten, en dan herimplementeren in Ember context hier.

**Comment by Wolfr** [comment]
Low prio want die alert stack fixen op zich is nog wel een ander paar mouwen (met dat die zo constant flasht)

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2917
