### ISSUE TITLE
In de arguments list van badge staat er niet bij dat @icon een mogelijk argument is

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#793]
http://localhost:4200/styleguide/badge

In de arguments list van badge staat er niet bij dat @icon een mogelijk argument is.

Beschrijving kan gelijkaardig zijn als deze in de documentatie hier: http://development.kaleidos-prototype.mono.digital/styleguide/auk-badge.html

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2896
