### ISSUE TITLE
Modals: meer documentatie van de verschillende opties

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#794]
De modals die momenteel in de styleguide staan

![image](https://user-images.githubusercontent.com/12690/113144962-257c8300-922e-11eb-9e13-707e0fdc7617.png)

Die hebben precies geen max breedte/sizes,

Beter gelijkaardige code documenteren zoals op http://development.kaleidos-prototype.mono.digital/styleguide/auk-modal-sizes.html .

Eventueel in een elegant ember component steken.

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2916
