### ISSUE TITLE
Algemene bedoeling: prototype styleguide zoveel mogelijk syncen naar een Ember versie

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#795]
Algemeen is 1 van de nieuwe hoofdtaken de prototype styleguide zoveel mogelijk syncen naar een Ember versie.

In de styleguide in prototype wordt reeds veel weergegeven dat wenselijk is en up to date met de designs.

We moeten stukje bij beetje syncen, en vertaling maken naar Ember. Deze issue kan dienen als master issue, en we kunnen voor elk component bekijken wat het werk is en hoe we er juist aan werken.

**Comment by brenner-company** [comment]
### Status synchronisatie

- [x] **au-color-badge**
  - [x] Component
  - [x] Documentation
- [x] **au-avatar** (review needed)
  - [x] Component
  - [x] Documentation

---

_Voor de status van de CSS synchronisatie van `au-kaleidos-css` met `kaleidos-prototype-v3`: https://github.com/kanselarij-vlaanderen/au-kaleidos-css/issues/8_

**Comment by brenner-company** [comment]
Dit ticket is ofwel afgerond of niet meer van toepassing en mag afgesloten worden.
