### ISSUE TITLE
Bewerken knop bij Ministers en Beleidsvelden heeft verkeerde icoon

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#796]
![image](https://user-images.githubusercontent.com/12690/113146055-822c6d80-922f-11eb-9fba-a581a5e70c03.png)

Cog icoon ipv edit icoon.

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2895
