### ISSUE TITLE
Mooiere syntax style voor code blocks (gebruiken wat reeds ontwikkeld is)

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#797]
![image](https://user-images.githubusercontent.com/12690/113146429-f36c2080-922f-11eb-921c-5c1cc579fda1.png)

Op het ember prototype ad ik een mooiere syntax style die bij de rest van de stijlen past geinclude.

Dit is in het vertaalproces er precies afgevallen.

Voorbeeld: http://development.kaleidosemberdemo.mono.digital/styleguide/dropdown

Todo: zoeken hoe we dit toch kunnen implementeren op `/styleguide` in de front-end.

**Comment by Wolfr** [comment]
Dit is gewoon kwestie van de juiste prism stylesheet te includen.

https://github.com/mono-company/kaleidos-ember-prototype/blob/master/app/styles/_prism.scss

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2924
