### ISSUE TITLE
vlc-button occurences weg refactoren

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#799]
![image](https://user-images.githubusercontent.com/12690/113147772-6c1fac80-9231-11eb-812d-7380b42804ca.png)

Zou niet meer mogen voorkomen in de HTML wegens gebruik AuButton

**Comment by brenner-company** [comment]
Aanpassingen op de volgende branch: DES/enhancement/732-vlc-refactor/button
