### ISSUE TITLE
Atoms zo veel mogelijk verschuiven naar logica Octane componenten

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#802]
Waar er losse buttons, badges, pills e.d. voorkomen, dit al zoveel mogelijk verzetten naar Octane syntax.

**Comment by Wolfr** [comment]
Dit blijft voor mij een hoofdprioriteit, om aan te werken, dat er zo weinig mogelijke losse elementen voorkomen.

**Comment by Wolfr** [comment]
In principe is dit iets dat iedereen in het team zou moeten weten, met een soort regel: als je iets ziet dat niet in Octane staat, verzet het! 

Mss op te nemen op algemene sprint planning @erikap .

**Comment by brenner-company** [comment]
Dit ticket is ofwel afgerond of niet meer van toepassing en mag afgesloten worden.
