### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#803]
In referentie naar #716 .

Nakijken hoe we een betere multi select kunnen maken binnen de Ember context, voor toepassing in de UI in het algemeen.

Suggesties om dit gedaan te krijgen:

*  recycleren van een ander project;
* eens bespreken met RP of zij hier een aparte Ember addon voor zien zitten
* over Ember power select dingen opzoeken - 

cc @MikiDi 

https://github.com/kanselarij-vlaanderen/kaleidos-frontend/issues/716

**Comment by MikiDi** [comment]
Power-select is niet perfect, maar toch de meest complete / best maintained select-addon die ik ken. Veronderstellende dat je met "beter" vooral meer customized styling bedoelt, maar de interactie van power-select wel goed vindt, zou een kleine analyse van [de customization mogelijkheden](https://ember-power-select.com/docs/styles) ([alle sass variables](https://github.com/cibernox/ember-power-select/blob/master/app/styles/ember-power-select/variables.scss)) wenselijk zijn. Als dat volstaat is het maar een kwestie van implementeren.  
Los van het multi-select-specifieke gaan we eens een technische story moeten voorzien om de power-select addon up-to-date te krijgen in kaleidos. Dat is dan ook de gelegenheid om gebruik te maken van de customization-variables ipv de default class van power-select te gaan overschrijven (dat herinner ik me toch correct, dat het in Kaleidos nu zo gebeurt hé?)

**Comment by Wolfr** [comment]
Power select is niet accessible. De author lijkt mij min of meer gestopt met maintenance, er staan daar 30 open PRs.

Wellicht is het nog altijd de beste oplossing; maar het moet onderzocht worden en er moet op gewerkt worden. Met betere styling gaat het dan over een CSS toepassing zodat

dit

![image](https://user-images.githubusercontent.com/12690/113278495-469eab80-92e2-11eb-9e31-d6c897954f3b.png)

meer gaat lijken op dit

![image](https://user-images.githubusercontent.com/12690/113278517-4ef6e680-92e2-11eb-8bd0-79d417f1b3ff.png)

(in hoeverre dat mogelijk is)

**Comment by Wolfr** [comment]
De mockup in vorige comment is een beetje out of date we hebben de check marks links gezet in de laatste versie van selects.

![image](https://user-images.githubusercontent.com/12690/114151902-eaf5a300-991d-11eb-929e-1868e2fa218d.png)

**Comment by Wolfr** [comment]
De multi select heeft nu zijn eigen Figma pagina. https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/WU3-Kaleidos-Master-Library-Design-patterns?node-id=2955%3A9

**Comment by brenner-company** [comment]
Issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2915
