### ISSUE TITLE
Status select

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#804]
Voor openbaarheid van een document

![image](https://user-images.githubusercontent.com/12690/113270208-88772400-92d9-11eb-903a-cb48d939472b.png)

**Comment by Wolfr** [comment]
Fanny gaat hier een duidelijker design voor maken.

@MikiDi ik denk dat jij hier ooit al eens power select voor gecustomized had, kan je die referentie die je al een paar keer gegeven hebt daarover nog eens geven?

**Comment by Wolfr** [comment]
Wij hebben gewerkt aan duidelijkere designs voor de verschillende pickers.

Zie Figma library:
https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/WU3-Kaleidos-Master-Library-Design-patterns?node-id=2753%3A990

**Comment by Wolfr** [comment]
De status picker heeft nu zijn eigen Figma artboard.
https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/WU3-Kaleidos-Master-Library-Design-patterns?node-id=2948%3A4891

**Comment by brenner-company** [comment]
Issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2914
