### ISSUE TITLE
Strategie voor complexe componenten

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#813]
Ik heb nagedacht over een strategie voor de complexe componenten.

* Eerst de CSS naar een nieuwe package versie, (van au-kaleidos-css) terug package-izen dus,
* Dit releasen, zodat we een duidelijke referentie hebben van de CSS state

* Dan nieuwe Ember app opstarten, volledig nieuwe repo, waar we die CSS package inladen
* In die Ember app prototypes maken van de verschillende componenten
  * Select custom met power select (single - multiple) + status variant #804 
  * Accordion #801 
  * Uploader #815 
  * Datepicker #814 

* Rechtstreeks in application.hbs een aantal voorbeelden zetten, zodat dit vlot demobaar is

### Review werk

* Code kwaliteit CSS bespreken met mij
* Demo's bespreken met Ember experts bij RedPencil
* Werk vergelijken met werk aan LBLOD kant (AU)

**Comment by brenner-company** [comment]
Dit ticket is ofwel afgerond of niet meer van toepassing en mag afgesloten worden.
