### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#814]
Duet datepicker gebruiken ter vervanging van WebUniversum datepicker

* Is toegankelijk
* Ziet er beter uit

**Comment by Wolfr** [comment]
Er is discussie over deze date picker op [rocket chat](https://chat.semte.ch/group/appuniversum/thread/Qr4ESgrPmD755Spt7).

Figma file is aangepast om aan te sluiten op Duet date picker ([library page link](https://www.figma.com/file/8tKG5CYiDDFPWJJ62kPYTj/WU3-Kaleidos-Master-Library-Design-patterns?node-id=553%3A50)).

**Comment by brenner-company** [comment]
Issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2913
