### ISSUE TITLE
Show disabled state for button

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#827]
Show disabled state for button in the style guide.

Disabled should be a property available on Button, if it's not, we need to add it.

Should be documented as an argument here:
https://kaleidos-dev.vlaanderen.be/styleguide/button-types

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2912
