### ISSUE TITLE
Remove Button (loading)

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#828]
Remove this type of button from the style guide, as we will not be using it this way.

https://kaleidos-dev.vlaanderen.be/styleguide/button-loading

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2894
