### ISSUE TITLE
De modal van filter publicaties is te breed + Titel veranderen.

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#834]
![image](https://user-images.githubusercontent.com/12690/114557213-bb220480-9c69-11eb-92f1-98c5b6f4a305.png)

De modal "Filter inhoud" van publicaties is te breed, en heeft ook een verkeerde titel (Filter publicaties). We hebben er voor gekozen om overal dezelfde titel "Filter inhoud" te gaan gebruiken (ook op andere plekken waar dit gaat voorkomen)

**Comment by Wolfr** [comment]
Ook de modal van dossier aanmaken is te breed, misschien moet de default breedte van de modal kleiner worden?

![image](https://user-images.githubusercontent.com/12690/114557708-3a173d00-9c6a-11eb-8730-d202b78b8b6c.png)

Iemand heeft mss de default breedte verzet?
Is er een manier om een size aan een modal mee te geven momenteel via een bepaald Component argument?

**Comment by brenner-company** [comment]
Kleinere issue's zoals deze worden vanaf nu binnen Jira geplaatst. Item staat nu onder: https://kanselarij.atlassian.net/browse/KAS-2901
